CREATE TABLE cidade (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	id_estado BIGINT(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE cidade ADD FOREIGN KEY (id_estado) REFERENCES estado (id)

